use leeperj28;

DROP TABLE IF EXISTS TEACHER;

create table TEACHER (
  TEACH_ID int unsigned not null auto_increment,
  TEACH_FNAME varchar(15) not null,
  TEACH_LNAME varchar(15) not null,
  TEACH_PHONE NUMERIC(10) null,
  primary key (TEACH_ID));

DROP TABLE IF EXISTS STUDENT;

create table STUDENT (
  STU_ID int unsigned not null auto_increment,
  STU_FNAME varchar(15) not null,
  STU_LNAME VARCHAR(15) NOT NULL,
  STU_PHONE NUMERIC(10) NULL,
  STU_BALANCE DECIMAL(5,2) NULL,
  STU_ENROLLDATE DATETIME NOT NULL,
  PRIMARY KEY (STU_ID));

DROP TABLE IF EXISTS TUTORIAL;

CREATE TABLE TUTORIAL (
  TUT_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  TEACH_ID INT UNSIGNED NOT NULL,
  PRIMARY KEY (TUT_ID),
  FOREIGN KEY (TEACH_ID) REFERENCES TEACHER(TEACH_ID));

DROP TABLE IF EXISTS ENROLL;

CREATE TABLE ENROLL (
  TUT_ID INT UNSIGNED NOT NULL,
  STU_ID INT UNSIGNED NOT NULL,
  ENROLL_GRADE VARCHAR(2),
  PRIMARY KEY (TUT_ID, STU_ID),
  FOREIGN KEY (TUT_ID) REFERENCES TUTORIAL(TUT_ID),
  FOREIGN KEY (STU_ID) REFERENCES STUDENT(STU_ID));



